# Generated by Django 6.0 on 2025-12-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageversion',
            name='archive',
        ),
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='packages/%Y/%m/')),
                ('os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('any', 'Any / Source')], default='any', max_length=20)),
                ('architecture', models.CharField(choices=[('x86_64', 'x86_64 (Intel/AMD 64-bit)'), ('arm64', 'ARM64 (Apple Silicon, RPi)'), ('any', 'Any / Universal')], default='any', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='packages.packageversion')),
            ],
            options={
                'unique_together': {('version', 'os', 'architecture')},
            },
        ),
    ]
