# Generated by Django 6.0 on 2025-12-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_packageversion_archive_packagefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='package',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='license',
            field=models.CharField(blank=True, default='MIT', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='repository',
            field=models.URLField(blank=True, help_text='Github/Gitlab URL', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagefile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='readme',
            field=models.TextField(blank=True, help_text='Markdown content extracted from the zip'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown in lists'),
        ),
    ]
